In [6]:
import numpy as np
import matplotlib.pyplot as plt
import gymnasium as gym
import random

print(np.exp(2))

7.38905609893065


In [ ]:
qtable = np.zeros((25,4))
print(qtable)
left = 0
down = 1
right = 2
UP = 3
random.choice(['left','right','up','down'])
env.action_space.sample()


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
import numpy as np
import pygame
import time
import gymnasium as gym
from gymnasium import spaces

# =========================
# 1. ENVIRONMENT
# =========================
class MazeEnv(gym.Env):
    def __init__(self):
        self.size = 3
        self.start = (0, 0)
        self.state = self.start
        self.cheese = (2, 2)
        self.wall = (1, 1)

        self.action_space = spaces.Discrete(4)
        self.observation_space = spaces.MultiDiscrete([3, 3])

    def reset(self, seed=None, options=None):
        self.state = self.start
        return np.array(self.state), {}

    def step(self, action):
        r, c = self.state

        # movement
        if action == 0: r -= 1  # up
        elif action == 1: r += 1  # down
        elif action == 2: c -= 1  # left
        elif action == 3: c += 1  # right

        # bounds check
        if r < 0 or r > 2 or c < 0 or c > 2:
            r, c = self.state

        new_state = (r, c)
        reward = -0.1  # step cost

        if new_state == self.wall:
            reward = -1
            new_state = self.state

        elif new_state == self.cheese:
            reward = 10

        self.state = new_state
        done = (self.state == self.cheese)

        return np.array(self.state), reward, done, False, {}


# =========================
# 2. VISUALIZATION (PYGAME)
# =========================
pygame.init()
CELL_SIZE = 120
GRID_SIZE = 3
WIDTH = HEIGHT = CELL_SIZE * GRID_SIZE

screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Rat Maze RL")

def draw(env):
    screen.fill((255, 255, 255))

    for r in range(GRID_SIZE):
        for c in range(GRID_SIZE):
            rect = pygame.Rect(c*CELL_SIZE, r*CELL_SIZE, CELL_SIZE, CELL_SIZE)

            # draw cell borders
            pygame.draw.rect(screen, (200, 200, 200), rect, 1)

            if (r, c) == env.wall:
                pygame.draw.rect(screen, (0, 0, 0), rect)

            elif (r, c) == env.cheese:
                pygame.draw.rect(screen, (255, 255, 0), rect)

            elif (r, c) == env.state:
                pygame.draw.rect(screen, (0, 0, 255), rect)

    pygame.display.flip()
    time.sleep(0.2)


# =========================
# 3. Q-LEARNING SETUP
# =========================
Q = np.zeros((3, 3, 4))  # (row, col, action)

alpha = 0.5
gamma = 0.9
epsilon = 0.2


# =========================
# 4. TRAINING LOOP
# =========================
env = MazeEnv()

for episode in range(50):
    state, _ = env.reset()
    done = False

    print(f"\nEpisode {episode}")

    while not done:
        # handle pygame quit
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                exit()

        r, c = state

        # epsilon-greedy action
        if np.random.rand() < epsilon:
            action = np.random.randint(4)
        else:
            action = np.argmax(Q[r, c])

        next_state, reward, done, _, _ = env.step(action)
        nr, nc = next_state

        # ===== Q UPDATE =====
        old_q = Q[r, c, action]
        max_future = np.max(Q[nr, nc])

        rpe = reward + gamma * max_future - old_q  # reward prediction error
        Q[r, c, action] += alpha * rpe

        print(f"State: {(r,c)} Action: {action} Reward: {reward:.2f} RPE: {rpe:.2f}")

        state = next_state

        draw(env)

print("\nTraining complete!")
pygame.quit()

ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5204:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5204:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1342:(snd_func_refer) error evaluating name
ALSA lib conf.c:5204:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5727:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM default



Episode 0
State: (np.int64(0), np.int64(0)) Action: 0 Reward: -0.10 RPE: -0.10


error: display Surface quit

: 